### ISSUE TITLE
Register Form

### ISSUE THREAD

**Issue by lukzgois** [lukzgois/ENDERC#2]
Create a form to register a new user.

## Form Fields

- name: `required`
- nickname: `required`
- password: `required, confirmed`
- date of birth: `required, date, must be at least 18yo`
- rg: `required`
- cpf: `required`
- address: `required`
- city: `required`
- state: `required`
- zipcode: `required`
- WhatsApp number: `required, phone number`
- Instagram profile `optional`
- emergency contact name: `required`
- emergency contact phone: `required, phone number`
- club: `required`
- allergies: `optional`
- blood_type: `required`
- food_restrictions: `optional`
- are you a guest?: `optional`
- do you agree with the terms and conditions?: `required, must be true`

## Behavior

The form must validate the fields.
If all fields are valid:
  - A new user should be created
  - The user must be logged in
  - The user must be redirected to the dashboard
  - An email should be sent to the user

## Tasks

- [ ] Create the register form
- [ ] Validate the required fields
- [ ] Create a new user
- [ ] Login the user
- [ ] Redirect the user to the dashboard
- [ ] Send the welcome email
